# Copyright 2017-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.3.2

EAPI=7

CRATES="
	aho-corasick-0.7.18
	atty-0.2.14
	autocfg-1.0.1
	bitflags-1.2.1
	block-buffer-0.9.0
	cfg-if-1.0.0
	clap-3.0.0-beta.2
	clap_derive-3.0.0-beta.2
	cpufeatures-0.1.5
	digest-0.9.0
	dirs-next-2.0.0
	dirs-sys-next-0.1.2
	env_logger-0.8.4
	generic-array-0.14.4
	getopts-0.2.21
	getrandom-0.2.3
	hashbrown-0.11.2
	heck-0.3.3
	hermit-abi-0.1.19
	humantime-2.1.0
	indexmap-1.7.0
	itertools-0.4.19
	itoa-0.4.7
	lazy_static-0.1.16
	lazy_static-1.4.0
	libc-0.2.98
	log-0.4.14
	memchr-2.4.0
	opaque-debug-0.3.0
	os_str_bytes-2.4.0
	ppv-lite86-0.2.10
	proc-macro-error-1.0.4
	proc-macro-error-attr-1.0.4
	proc-macro2-1.0.27
	pulldown-cmark-0.8.0
	quote-1.0.9
	rand-0.8.4
	rand_chacha-0.3.1
	rand_core-0.6.3
	rand_hc-0.3.1
	redox_syscall-0.2.9
	redox_users-0.4.0
	regex-1.5.4
	regex-syntax-0.6.25
	remove_dir_all-0.5.3
	rustc_version-0.1.7
	ryu-1.0.5
	scan-rules-0.2.0
	semver-0.1.20
	serde-1.0.126
	serde_derive-1.0.126
	serde_json-1.0.64
	sha-1-0.9.6
	strcursor-0.2.5
	strsim-0.10.0
	syn-1.0.73
	tempfile-3.2.0
	termcolor-1.1.2
	textwrap-0.12.1
	toml-0.5.8
	typenum-1.13.0
	unicase-2.6.0
	unicode-segmentation-0.1.2
	unicode-segmentation-1.8.0
	unicode-width-0.1.8
	unicode-xid-0.2.2
	vec_map-0.8.2
	version_check-0.9.3
	wasi-0.10.2+wasi-snapshot-preview1
	winapi-0.3.9
	winapi-i686-pc-windows-gnu-0.4.0
	winapi-util-0.1.5
	winapi-x86_64-pc-windows-gnu-0.4.0
	winreg-0.7.0
"

inherit cargo

DESCRIPTION="Command-line tool to run Rust "scripts" which can make use of crates."
# Double check the homepage as the cargo_metadata crate
# does not provide this value so instead repository is used
HOMEPAGE="https://github.com/fornwall/rust-script"
SRC_URI="https://github.com/fornwall/rust-script/archive/refs/tags/v${PV}.tar.gz $(cargo_crate_uris ${CRATES})"

# License set may be more restrictive as OR is not respected
# use cargo-license for a more accurate license picture
LICENSE="Apache-2.0 MIT Unlicense"
SLOT="0"
KEYWORDS="~amd64"
RESTRICT="mirror"
